name=EMOttoDIYLib
version=1.0.0
author=Marco Mortari basata su libreria Otto DIY, Camilo Parra Palacio
maintainer=@mmortari
sentence=Libreria personalizzata per EMOtto
paragraph=Versione modificata di OttoDIYLib. OTTIMIZZATA PER esp32
category=Device Control
url=
architectures= esp32
includes=EMOtto.h
